-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CEN4020
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CEN4020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CEN4020` DEFAULT CHARACTER SET utf8 ;
USE `CEN4020` ;

-- -----------------------------------------------------
-- Table `CEN4020`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEN4020`.`users` (
  `username` NVARCHAR(45) NOT NULL,
  `first` NVARCHAR(45) NOT NULL,
  `last` NVARCHAR(45) NOT NULL,
  `passhash` BINARY(64) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `idusers_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEN4020`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEN4020`.`projects` (
  `projectID` INT NOT NULL,
  `projectName` NVARCHAR(45) NOT NULL,
  `projectStart` DATE NOT NULL,
  PRIMARY KEY (`projectID`),
  UNIQUE INDEX `projectID_UNIQUE` (`projectID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEN4020`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEN4020`.`tasks` (
  `taskID` INT NOT NULL,
  `taskStart` DATE NOT NULL,
  `username` NVARCHAR(45) NULL,
  `projectID` INT NOT NULL,
  PRIMARY KEY (`taskID`),
  UNIQUE INDEX `taskID_UNIQUE` (`taskID` ASC),
  INDEX `fk_tasks_users_idx` (`username` ASC),
  INDEX `fk_tasks_projects1_idx` (`projectID` ASC),
  CONSTRAINT `fk_tasks_users`
    FOREIGN KEY (`username`)
    REFERENCES `CEN4020`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_projects1`
    FOREIGN KEY (`projectID`)
    REFERENCES `CEN4020`.`projects` (`projectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEN4020`.`belongTo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEN4020`.`belongTo` (
  `username` NVARCHAR(45) NOT NULL,
  `projectID` INT NOT NULL,
  `permissions` INT NOT NULL,
  PRIMARY KEY (`username`, `projectID`),
  INDEX `fk_users_has_projects_projects1_idx` (`projectID` ASC),
  INDEX `fk_users_has_projects_users1_idx` (`username` ASC),
  CONSTRAINT `fk_users_has_projects_users1`
    FOREIGN KEY (`username`)
    REFERENCES `CEN4020`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_projects_projects1`
    FOREIGN KEY (`projectID`)
    REFERENCES `CEN4020`.`projects` (`projectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CEN4020`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CEN4020`.`comments` (
  `commentID` INT NOT NULL,
  `text` VARCHAR(256) NULL,
  `commentDate` DATE NOT NULL,
  `username` NVARCHAR(45) NOT NULL,
  `projectID` INT NOT NULL,
  PRIMARY KEY (`commentID`),
  UNIQUE INDEX `commentID_UNIQUE` (`commentID` ASC),
  INDEX `fk_comments_users1_idx` (`username` ASC),
  INDEX `fk_comments_projects1_idx` (`projectID` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`username`)
    REFERENCES `CEN4020`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_projects1`
    FOREIGN KEY (`projectID`)
    REFERENCES `CEN4020`.`projects` (`projectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
